### ISSUE TITLE
`shard_tests::test_read_write_at` failing in `master`

### ISSUE THREAD

**Issue by luiz10x** [10XGenomics/rust-shardio#40]
While working on #39 I noticed that `shard_tests::test_read_write_at` fails when running the full test suite (`cargo t --release --features full-test`). I didn't start bisecting yet to find when it changed/started failing, but are the full tests too much to run in CI?

**Comment by pmarks** [comment]
I've enabled this test full-time & switched to using `read_exact` and `write_all` in #42 so this should be fixed.
