### ISSUE TITLE
Missing tags for releases?

### ISSUE THREAD

**Issue by bgianfo** [10XGenomics/rust-shardio#49]
@pmarks Do you by chance have some local tags that you haven't pushed to the repo during release of the crate? 

The repos is tagged only up to `0.7.1`, but crates.io shows version `0.8.2` being available?

**Comment by pmarks** [comment]
I was remiss in tagging the commit that I `cargo publish`ed. Fixed now.

**Comment by bgianfo** [comment]
Thanks!
